# Generated by Django 5.2.15 on 2026-06-05 09:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='入库单号')),
                ('doc_date', models.DateField(verbose_name='入库日期')),
                ('purchase_type', models.CharField(choices=[('external', '外购'), ('borrow', '借调')], default='external', max_length=16, verbose_name='采购方式')),
                ('status', models.CharField(choices=[('posted', '已过账'), ('void', '已作废')], default='posted', max_length=12, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('total_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='总数量')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='总金额')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购入库单',
                'verbose_name_plural': '采购入库单',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInboundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='成本单价')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='金额')),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseinbound', verbose_name='入库单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product', verbose_name='商品')),
                ('stock_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockmove', verbose_name='对应流水')),
            ],
            options={
                'verbose_name': '采购入库明细',
                'verbose_name_plural': '采购入库明细',
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseinbound',
            constraint=models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_inbound_company_docno'),
        ),
    ]
