# Generated by Django 5.2.15 on 2026-06-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseinbound_source_outbound'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinbound',
            options={'ordering': ['-doc_date', '-id'], 'permissions': [('void_purchaseinbound', '作废采购入库单')], 'verbose_name': '采购入库单', 'verbose_name_plural': '采购入库单'},
        ),
    ]
