# Generated by Django 5.2.15 on 2026-06-06 00:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchaseinbound_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinbound',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='税额合计'),
        ),
        migrations.AddField(
            model_name='purchaseinbound',
            name='total_taxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='含税合计'),
        ),
        migrations.AddField(
            model_name='purchaseinbound',
            name='total_untaxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='不含税合计'),
        ),
        migrations.AddField(
            model_name='purchaseinboundline',
            name='amount_taxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='含税金额'),
        ),
        migrations.AddField(
            model_name='purchaseinboundline',
            name='amount_untaxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='不含税金额'),
        ),
        migrations.AddField(
            model_name='purchaseinboundline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='税额'),
        ),
        migrations.AddField(
            model_name='purchaseinboundline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.13'), max_digits=5, verbose_name='税率'),
        ),
        migrations.AlterField(
            model_name='purchaseinbound',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='入库成本合计'),
        ),
        migrations.AlterField(
            model_name='purchaseinboundline',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='入库成本金额'),
        ),
        migrations.AlterField(
            model_name='purchaseinboundline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='不含税单价'),
        ),
    ]
