# Generated by Django 5.2.15 on 2026-07-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseinbound_total_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinbound',
            name='is_opening',
            field=models.BooleanField(default=False, help_text='期初导入的已入库未收票；不重复加库存', verbose_name='期初应付暂估'),
        ),
    ]
