# Generated by Django 5.2.15 on 2026-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_purchase_order_m18'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinbound',
            name='purchase_type',
            field=models.CharField(choices=[('external', '外购'), ('borrow', '借调'), ('purchase_return', '采购退回')], default='external', max_length=16, verbose_name='采购方式'),
        ),
    ]
