# Generated by Django 5.2.15 on 2026-07-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_partner_fk_and_proxies'),
        ('purchasing', '0008_alter_fk_to_businesspartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinbound',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='供应商'),
        ),
    ]
