# Generated by Django 5.2.15 on 2026-06-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseinbound_source_outbound'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoutbound',
            name='mirror_inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='purchasing.purchaseinbound', verbose_name='关联镜像入库单'),
        ),
    ]
