# Generated by Django 5.2.15 on 2026-06-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesoutbound_mirror_inbound'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesoutbound',
            options={'ordering': ['-doc_date', '-id'], 'permissions': [('void_salesoutbound', '作废销售出库单')], 'verbose_name': '销售出库单', 'verbose_name_plural': '销售出库单'},
        ),
    ]
