# Generated by Django 5.2.15 on 2026-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesoutbound_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoutbound',
            name='sales_type',
            field=models.CharField(choices=[('sale', '销售'), ('lend', '借出'), ('return', '归还')], default='sale', max_length=16, verbose_name='销售方式'),
        ),
    ]
