# Generated by Django 5.2.15 on 2026-06-06 00:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesoutbound_sales_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoutbound',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='税额合计'),
        ),
        migrations.AddField(
            model_name='salesoutbound',
            name='total_taxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='含税售额合计'),
        ),
        migrations.AddField(
            model_name='salesoutbound',
            name='total_untaxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='不含税售额合计'),
        ),
        migrations.AddField(
            model_name='salesoutboundline',
            name='amount_taxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='含税金额'),
        ),
        migrations.AddField(
            model_name='salesoutboundline',
            name='amount_untaxed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='不含税金额'),
        ),
        migrations.AddField(
            model_name='salesoutboundline',
            name='sale_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='销售单价(不含税)'),
        ),
        migrations.AddField(
            model_name='salesoutboundline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='税额'),
        ),
        migrations.AddField(
            model_name='salesoutboundline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.13'), max_digits=5, verbose_name='税率'),
        ),
        migrations.AlterField(
            model_name='salesoutbound',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='结转成本合计'),
        ),
    ]
