# Generated by Django 5.2.15 on 2026-07-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesoutbound_total_tax_salesoutbound_total_taxed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesoutbound',
            name='is_opening',
            field=models.BooleanField(default=False, help_text='期初导入的已出库未开票；不重复减库存', verbose_name='期初发出商品'),
        ),
    ]
