# Generated by Django 5.2.15 on 2026-07-15 04:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_period_closed_through'),
        ('masterdata', '0004_alter_invoicequota_options_and_more'),
        ('sales', '0006_opening_goods_shipped_ap_accrual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='订单号')),
                ('doc_date', models.DateField(verbose_name='订单日期')),
                ('status', models.CharField(choices=[('open', '执行中'), ('closed', '已关闭'), ('void', '已作废')], default='open', max_length=12, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('total_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='订单总数量')),
                ('total_untaxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='不含税合计')),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='税额合计')),
                ('total_taxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='含税合计')),
                ('ship_status', models.CharField(choices=[('none', '未发生'), ('partial', '部分'), ('full', '全部')], default='none', max_length=12, verbose_name='发货状态')),
                ('invoice_status', models.CharField(choices=[('none', '未发生'), ('partial', '部分'), ('full', '全部')], default='none', max_length=12, verbose_name='开票状态')),
                ('receipt_status', models.CharField(choices=[('none', '未发生'), ('partial', '部分'), ('full', '全部')], default='none', max_length=12, verbose_name='收款状态')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='salesoutbound',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbounds', to='sales.salesorder', verbose_name='来源销售订单'),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=10, verbose_name='行号')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='订单数量')),
                ('sale_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='销售单价(不含税)')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.13'), max_digits=5, verbose_name='税率')),
                ('amount_untaxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='不含税金额')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='税额')),
                ('amount_taxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='含税金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder', verbose_name='销售订单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '销售订单明细',
                'verbose_name_plural': '销售订单明细',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.AddField(
            model_name='salesoutboundline',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_lines', to='sales.salesorderline', verbose_name='来源订单行'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_salesorder_company_docno'),
        ),
    ]
