# Generated by Django 5.2.15 on 2026-07-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_m18_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesoutbound',
            name='sales_type',
            field=models.CharField(choices=[('sale', '销售'), ('lend', '借出'), ('return', '归还'), ('sale_return', '销售退回')], default='sale', max_length=16, verbose_name='销售方式'),
        ),
    ]
