# Generated by Django 5.2.15 on 2026-07-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_partner_fk_and_proxies'),
        ('sales', '0009_alter_fk_to_businesspartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='salesoutbound',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='客户'),
        ),
    ]
