# Generated by Django 5.2.15 on 2026-06-05 10:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='账户名称')),
                ('bank_name', models.CharField(blank=True, max_length=128, verbose_name='开户行')),
                ('account_no', models.CharField(blank=True, max_length=64, verbose_name='银行账号')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='启用日银行存款余额；后续以日记账增减。', max_digits=18, verbose_name='期初余额')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '银行账户',
                'verbose_name_plural': '银行账户',
                'ordering': ['company', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_bankaccount_company_name')],
            },
        ),
    ]
