# Generated by Django 5.2.15 on 2026-06-05 11:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0002_purchaseinvoice_purchaseinvoiceline_and_more'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(verbose_name='日期')),
                ('direction', models.CharField(choices=[('in', '收入'), ('out', '支出')], max_length=4, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('counterparty', models.CharField(blank=True, max_length=128, verbose_name='对方单位')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Excel导入')),
                ('source_type', models.CharField(blank=True, max_length=32, verbose_name='来源类型')),
                ('source_id', models.CharField(blank=True, max_length=32, verbose_name='来源ID')),
                ('source_no', models.CharField(blank=True, max_length=64, verbose_name='来源单号')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='finance.bankaccount', verbose_name='银行账户')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '银行存款日记账',
                'verbose_name_plural': '银行存款日记账',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='付款单号')),
                ('doc_date', models.DateField(verbose_name='付款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='付款金额')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='已核销金额')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('status', models.CharField(choices=[('posted', '已登记'), ('void', '已作废')], default='posted', max_length=12, verbose_name='状态')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount', verbose_name='付款银行账户')),
                ('bank_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.bankjournal', verbose_name='对应日记账')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='收款供应商')),
            ],
            options={
                'verbose_name': '付款登记',
                'verbose_name_plural': '付款登记',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='bankjournal',
            index=models.Index(fields=['company', 'bank_account', 'date'], name='finance_ban_company_0cd383_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_payment_company_docno'),
        ),
    ]
