# Generated by Django 5.2.15 on 2026-06-05 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_bankjournal_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='核销金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='核销时间')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.purchaseinvoice', verbose_name='采购发票')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment', verbose_name='付款')),
            ],
            options={
                'verbose_name': '应付核销',
                'verbose_name_plural': '应付核销',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
