# Generated by Django 5.2.15 on 2026-06-05 11:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0004_paymentallocation'),
        ('masterdata', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='收款单号')),
                ('doc_date', models.DateField(verbose_name='收款日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='收款金额')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='已核销金额')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('status', models.CharField(choices=[('posted', '已登记'), ('void', '已作废')], default='posted', max_length=12, verbose_name='状态')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount', verbose_name='收款银行账户')),
                ('bank_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.bankjournal', verbose_name='对应日记账')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='付款客户')),
            ],
            options={
                'verbose_name': '收款登记',
                'verbose_name_plural': '收款登记',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='登记单号')),
                ('invoice_no', models.CharField(blank=True, max_length=64, verbose_name='发票号码')),
                ('doc_date', models.DateField(verbose_name='开票日期')),
                ('amount_untaxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='不含税金额')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='税额')),
                ('amount_taxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='含税金额')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='已核销金额')),
                ('status', models.CharField(choices=[('registered', '已开具'), ('void', '已作废')], default='registered', max_length=12, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '销售发票',
                'verbose_name_plural': '销售发票',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='核销金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='核销时间')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.receipt', verbose_name='收款')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.salesinvoice', verbose_name='销售发票')),
            ],
            options={
                'verbose_name': '应收核销',
                'verbose_name_plural': '应收核销',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='摘要')),
                ('amount_untaxed', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='不含税金额')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.13'), max_digits=5, verbose_name='税率')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='税额')),
                ('amount_taxed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='含税金额')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.salesinvoice', verbose_name='发票')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.product', verbose_name='商品')),
                ('source_outbound_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesoutboundline', verbose_name='来源出库明细')),
            ],
            options={
                'verbose_name': '销售发票明细',
                'verbose_name_plural': '销售发票明细',
            },
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_receipt_company_docno'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_sinvoice_company_docno'),
        ),
    ]
