# Generated by Django 5.2.15 on 2026-06-05 11:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0005_receipt_salesinvoice_receiptallocation_and_more'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_kind', models.CharField(choices=[('ar_note', '应收票据'), ('ap_note', '应付票据')], max_length=10, verbose_name='票据类型')),
                ('note_id', models.PositiveIntegerField(verbose_name='票据ID')),
                ('note_no', models.CharField(blank=True, max_length=32, verbose_name='票据单号')),
                ('invoice_kind', models.CharField(choices=[('sales', '销售发票(应收)'), ('purchase', '采购发票(应付)')], max_length=10, verbose_name='发票类型')),
                ('invoice_id', models.PositiveIntegerField(verbose_name='发票ID')),
                ('invoice_no', models.CharField(blank=True, max_length=32, verbose_name='发票单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='冲销金额')),
                ('is_endorsement', models.BooleanField(default=False, verbose_name='背书抵付')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='冲销时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '票据冲销',
                'verbose_name_plural': '票据冲销',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotePayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='登记单号')),
                ('note_no', models.CharField(blank=True, max_length=64, verbose_name='票据号码')),
                ('draw_date', models.DateField(verbose_name='开票日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='票面金额')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='已用金额')),
                ('status', models.CharField(choices=[('issued', '已开出'), ('settled', '已结算'), ('void', '已作废')], default='issued', max_length=12, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Excel导入')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='收票供应商')),
            ],
            options={
                'verbose_name': '应付票据',
                'verbose_name_plural': '应付票据',
                'ordering': ['-draw_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_notepay_company_docno')],
            },
        ),
        migrations.CreateModel(
            name='NoteReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='登记单号')),
                ('note_no', models.CharField(blank=True, max_length=64, verbose_name='票据号码')),
                ('draw_date', models.DateField(verbose_name='出票日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='票面金额')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='已用金额')),
                ('status', models.CharField(choices=[('on_hand', '在手'), ('endorsed', '已背书'), ('settled', '已结算'), ('void', '已作废')], default='on_hand', max_length=12, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('is_imported', models.BooleanField(default=False, verbose_name='Excel导入')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='出票/来源客户')),
            ],
            options={
                'verbose_name': '应收票据',
                'verbose_name_plural': '应收票据',
                'ordering': ['-draw_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_notercv_company_docno')],
            },
        ),
    ]
