# Generated by Django 5.2.15 on 2026-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_notesettlement_notepayable_notereceivable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notepayable',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name='期初'),
        ),
        migrations.AddField(
            model_name='notereceivable',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name='期初'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name='期初'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_opening',
            field=models.BooleanField(default=False, verbose_name='期初'),
        ),
    ]
