# Generated by Django 5.2.15 on 2026-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_notepayable_is_opening_notereceivable_is_opening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(verbose_name='日期')),
                ('kind', models.CharField(choices=[('purchase', '采购入库'), ('sales', '销售出库')], max_length=12, verbose_name='来源类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('included_in_cost', models.BooleanField(default=False, verbose_name='计入存货成本')),
                ('source_no', models.CharField(blank=True, max_length=64, verbose_name='来源单号')),
                ('source_type', models.CharField(blank=True, max_length=32, verbose_name='来源单类型')),
                ('source_id', models.CharField(blank=True, max_length=32, verbose_name='来源单ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '其他费用',
                'verbose_name_plural': '其他费用',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
