# Generated by Django 5.2.15 on 2026-06-05 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0008_expenseentry'),
        ('masterdata', '0002_expensecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.expensecategory', verbose_name='费用类别'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
