# Generated by Django 5.2.15 on 2026-06-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0009_expenseentry_category_expenseentry_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('counterparty', models.CharField(max_length=128, verbose_name='对手单位')),
                ('direction', models.CharField(choices=[('in', '借入'), ('out', '归还')], max_length=4, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('date', models.DateField(verbose_name='日期')),
                ('source_type', models.CharField(blank=True, max_length=32, verbose_name='来源单类型')),
                ('source_id', models.CharField(blank=True, max_length=32, verbose_name='来源单ID')),
                ('source_no', models.CharField(blank=True, max_length=64, verbose_name='来源单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '借调往来',
                'verbose_name_plural': '借调往来',
                'ordering': ['counterparty', 'date', 'id'],
            },
        ),
    ]
