# Generated by Django 5.2.15 on 2026-06-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_borrowtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankjournal',
            name='txn_no',
            field=models.CharField(blank=True, help_text='网银流水唯一号；增量导入按「账户+流水号」去重。', max_length=64, verbose_name='交易流水号'),
        ),
    ]
