# Generated by Django 5.2.15 on 2026-06-06 02:46

from django.db import migrations, models


def backfill_entry_type(apps, schema_editor):
    """已有 Payment/Receipt 自动生成的日记账标为「往来结算」，其余(导入/历史)保持「其他」。"""
    BankJournal = apps.get_model("finance", "BankJournal")
    BankJournal.objects.filter(source_type__in=["Payment", "Receipt"]).update(entry_type="settlement")


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_bankjournal_txn_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankjournal',
            name='entry_type',
            field=models.CharField(choices=[('settlement', '往来结算'), ('expense', '费用'), ('tax', '税费'), ('payroll', '工资'), ('transfer', '内部划转'), ('other', '其他')], default='other', max_length=12, verbose_name='业务类型'),
        ),
        migrations.RunPython(backfill_entry_type, migrations.RunPython.noop),
    ]
