# Generated by Django 5.2.15 on 2026-06-06 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action'),
        ('finance', '0012_bankjournal_entry_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankjournal',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='已对账'),
        ),
        migrations.CreateModel(
            name='BankReconcileBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('period_from', models.DateField(blank=True, null=True, verbose_name='起始日期')),
                ('period_to', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('matched_count', models.IntegerField(default=0, verbose_name='已匹配数')),
                ('system_only_count', models.IntegerField(default=0, verbose_name='仅系统有数')),
                ('bank_only_count', models.IntegerField(default=0, verbose_name='仅网银有数')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconcile_batches', to='finance.bankaccount', verbose_name='银行账户')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '银行对账批次',
                'verbose_name_plural': '银行对账批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankjournal',
            name='reconcile_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_journals', to='finance.bankreconcilebatch', verbose_name='对账批次'),
        ),
    ]
