# Generated by Django 5.2.15 on 2026-06-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_bankjournal_reconciled_bankreconcilebatch_and_more'),
        ('masterdata', '0002_expensecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='收款供应商'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='付款客户'),
        ),
    ]
