# Generated by Django 5.2.15 on 2026-06-07 05:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_payment_supplier_alter_receipt_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='数量'),
        ),
    ]
