# Generated by Django 5.2.15 on 2026-06-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_purchaseinvoiceline_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='term_days',
            field=models.PositiveIntegerField(default=0, help_text='0=即期；到期日 = 开票日期 + 账期天数', verbose_name='账期(天)'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='term_days',
            field=models.PositiveIntegerField(default=0, help_text='0=即期；到期日 = 开票日期 + 账期天数', verbose_name='账期(天)'),
        ),
    ]
