# Generated by Django 5.2.15 on 2026-06-10 03:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_opening_locked'),
        ('finance', '0017_purchaseinvoice_term_days_salesinvoice_term_days'),
        ('masterdata', '0004_alter_invoicequota_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(choices=[('commission', '佣金'), ('sales', '销售费用'), ('admin', '管理费用'), ('finance', '财务费用')], max_length=16, verbose_name='类别')),
                ('date', models.DateField(verbose_name='日期')),
                ('person', models.CharField(blank=True, max_length=64, verbose_name='人员名称')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='金额')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='客户')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '费用记录',
                'verbose_name_plural': '费用记录',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
