# Generated by Django 5.2.15 on 2026-06-25 07:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_opening_locked'),
        ('finance', '0019_recompute_note_receivable_settled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankjournal',
            name='entry_type',
            field=models.CharField(choices=[('settlement', '往来结算'), ('expense', '费用'), ('tax', '税费'), ('payroll', '工资'), ('transfer', '内部划转'), ('note_cash', '票据兑现'), ('other', '其他')], default='other', max_length=12, verbose_name='业务类型'),
        ),
        migrations.CreateModel(
            name='NoteDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('collect', '到期兑付'), ('discount', '贴现')], max_length=10, verbose_name='处置方式')),
                ('date', models.DateField(verbose_name='处置日期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='票面金额')),
                ('discount_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='贴现息')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='实收净额')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount', verbose_name='收款银行账户')),
                ('bank_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankjournal', verbose_name='银行日记账')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expenserecord', verbose_name='贴现息费用记录')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='finance.notereceivable', verbose_name='应收票据')),
            ],
            options={
                'verbose_name': '票据处置',
                'verbose_name_plural': '票据处置',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
