# Generated by Django 5.2.15 on 2026-07-14 15:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_period_closed_through'),
        ('finance', '0021_allocation_settlement_date'),
        ('masterdata', '0004_alter_invoicequota_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercoBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kind', models.CharField(choices=[('other_ar', '其他应收·关联方'), ('other_ap', '其他应付·关联方')], max_length=16, verbose_name='科目')),
                ('direction', models.CharField(choices=[('in', '增加'), ('out', '减少')], max_length=4, verbose_name='方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('date', models.DateField(verbose_name='日期')),
                ('source_type', models.CharField(blank=True, max_length=32, verbose_name='来源类型')),
                ('source_id', models.CharField(blank=True, max_length=32, verbose_name='来源ID')),
                ('source_no', models.CharField(blank=True, max_length=64, verbose_name='来源单号')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('counterparty_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company', verbose_name='关联对手公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '关联方其他往来',
                'verbose_name_plural': '关联方其他往来',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='对冲单号')),
                ('doc_date', models.DateField(verbose_name='对冲日期')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='对冲金额')),
                ('status', models.CharField(choices=[('registered', '已登记'), ('void', '已撤销')], default='registered', max_length=12, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('voucher_hint', models.CharField(default='AR_AP_NET', editable=False, max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='客户')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '往来对冲',
                'verbose_name_plural': '往来对冲',
                'ordering': ['-doc_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerOffsetAPLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='对冲金额')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offset_ap_lines', to='finance.purchaseinvoice')),
                ('offset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_lines', to='finance.partneroffset')),
            ],
            options={
                'verbose_name': '往来对冲·应付行',
                'verbose_name_plural': '往来对冲·应付行',
            },
        ),
        migrations.CreateModel(
            name='PartnerOffsetARLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='对冲金额')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offset_ar_lines', to='finance.salesinvoice')),
                ('offset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_lines', to='finance.partneroffset')),
            ],
            options={
                'verbose_name': '往来对冲·应收行',
                'verbose_name_plural': '往来对冲·应收行',
            },
        ),
        migrations.CreateModel(
            name='NoteLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc_no', models.CharField(max_length=32, verbose_name='拆借单号')),
                ('doc_date', models.DateField(verbose_name='拆借日期')),
                ('role', models.CharField(choices=[('lend', '出借'), ('borrow', '借入')], max_length=8, verbose_name='本方角色')),
                ('note_kind', models.CharField(choices=[('receivable', '应收票据'), ('payable', '应付票据')], max_length=16, verbose_name='票据种类')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='拆借金额')),
                ('returned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='已归还金额')),
                ('status', models.CharField(choices=[('open', '在借'), ('closed', '已归还'), ('void', '已撤销')], default='open', max_length=12, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('voucher_hint', models.CharField(default='NOTE_LEND', editable=False, max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('counterparty_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company', verbose_name='对手公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mirror', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mirror_of', to='finance.noteloan')),
                ('note_payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='finance.notepayable')),
                ('note_receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='finance.notereceivable')),
            ],
            options={
                'verbose_name': '票据拆借',
                'verbose_name_plural': '票据拆借',
                'ordering': ['-doc_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_noteloan_company_docno')],
            },
        ),
        migrations.AddConstraint(
            model_name='partneroffset',
            constraint=models.UniqueConstraint(fields=('company', 'doc_no'), name='uniq_partneroffset_company_docno'),
        ),
    ]
