# Generated by Django 5.2.15 on 2026-07-15 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_m17_partner_offset_note_loan'),
        ('sales', '0007_m18_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesorder', verbose_name='来源销售订单'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='sales.salesorderline', verbose_name='来源订单行'),
        ),
    ]
