# Generated by Django 5.2.15 on 2026-07-15 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_m18_sales_order'),
        ('purchasing', '0006_purchase_order_m18'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchasing.purchaseorder', verbose_name='来源采购订单'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='purchasing.purchaseorderline', verbose_name='来源订单行'),
        ),
    ]
