# Generated by Django 5.2.15 on 2026-07-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_alter_fk_to_businesspartner'),
        ('masterdata', '0006_partner_fk_and_proxies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='notepayable',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='收票供应商'),
        ),
        migrations.AlterField(
            model_name='notereceivable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='出票/来源客户'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='收款供应商'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.supplier', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='付款客户'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.customer', verbose_name='客户'),
        ),
    ]
