# Generated by Django 5.2.15 on 2026-08-05 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_fk_point_proxy_customer_supplier'),
        ('purchasing', '0009_fk_point_proxy_customer_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchasing.purchaseorder', verbose_name='关联采购订单'),
        ),
    ]
