# Generated by Django 5.2.15 on 2026-08-05 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_payment_purchase_order'),
        ('purchasing', '0009_fk_point_proxy_customer_supplier'),
        ('sales', '0010_fk_point_proxy_customer_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesettlement',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_settlements', to='purchasing.purchaseorder', verbose_name='关联采购订单'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='sales.salesorder', verbose_name='关联销售订单'),
        ),
        migrations.AlterField(
            model_name='notesettlement',
            name='invoice_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='发票ID'),
        ),
        migrations.AlterField(
            model_name='notesettlement',
            name='invoice_kind',
            field=models.CharField(blank=True, choices=[('sales', '销售发票(应收)'), ('purchase', '采购发票(应付)')], default='', max_length=10, verbose_name='发票类型'),
        ),
    ]
