# Generated by Django 5.2.15 on 2026-06-05 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='公司编号')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='公司全称')),
                ('short_name', models.CharField(blank=True, max_length=32, verbose_name='简称')),
                ('is_related', models.BooleanField(default=True, verbose_name='系统内关联企业')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公司账套',
                'verbose_name_plural': '公司账套',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('void', '作废'), ('link', '关联联动'), ('offset', '冲销核销')], max_length=16, verbose_name='动作')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='对象类型')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='对象ID')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
