# Generated by Django 5.2.15 on 2026-06-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('void', '作废'), ('link', '关联联动'), ('offset', '冲销核销'), ('login', '登录')], max_length=16, verbose_name='动作'),
        ),
    ]
