# Generated by Django 5.2.15 on 2026-06-08 12:34

from django.db import migrations, models

# 按公司简称/全称关键字匹配，填入法定全称抬头（仅对空 full_name 的设置）
FULL_NAMES = [
    ("安博诺", "安博诺新材料科技（上海）有限公司"),
    ("恒本源", "上海恒本源化学有限公司"),
    ("鸿威达", "鸿威达新材料科技（上海）有限公司"),
]


def set_full_names(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    for kw, full in FULL_NAMES:
        for c in Company.objects.filter(full_name=""):
            if kw in (c.name or "") or kw in (c.short_name or ""):
                c.full_name = full
                c.save(update_fields=["full_name"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(blank=True, help_text='如「安博诺新材料科技（上海）有限公司」；用于 Excel 表头与单据打印抬头。留空则用公司全称。', max_length=128, verbose_name='法定全称（报表/单据抬头）'),
        ),
        migrations.RunPython(set_full_names, noop),
    ]
