# Generated by Django 5.2.15 on 2026-06-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='opening_locked',
            field=models.BooleanField(default=False, help_text='启用后期初数据不可修改/重导；未启用时可清空重导。', verbose_name='期初已启用(锁定)'),
        ),
    ]
