# Generated by Django 5.2.15 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_opening_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='period_closed_through',
            field=models.DateField(
                blank=True,
                help_text='该日及之前的业务单据不可修改/删除；月结时按顺序逐月推进。',
                null=True,
                verbose_name='会计期间已结账至',
            ),
        ),
    ]
