# Generated by Django 5.2.15 on 2026-06-05 08:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, verbose_name='编码')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('contact', models.CharField(blank=True, max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='电话')),
                ('tax_no', models.CharField(blank=True, max_length=32, verbose_name='税号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_company', models.ForeignKey(blank=True, help_text='当对方是系统内关联企业（C1/C2/C3）时选择；用于 M4 关联交易自动联动。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company', verbose_name='对应关联企业')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['company', 'code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_customer_company_code')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, verbose_name='商品编码')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('spec', models.CharField(blank=True, max_length=128, verbose_name='规格型号')),
                ('unit', models.CharField(blank=True, max_length=16, verbose_name='计量单位')),
                ('category', models.CharField(blank=True, max_length=64, verbose_name='分类')),
                ('default_tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.13'), max_digits=5, verbose_name='默认税率')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['company', 'code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_product_company_code')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, verbose_name='编码')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('contact', models.CharField(blank=True, max_length=64, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='电话')),
                ('tax_no', models.CharField(blank=True, max_length=32, verbose_name='税号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('related_company', models.ForeignKey(blank=True, help_text='当对方是系统内关联企业（C1/C2/C3）时选择；用于 M4 关联交易自动联动。', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.company', verbose_name='对应关联企业')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['company', 'code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_supplier_company_code')],
            },
        ),
    ]
