# Generated by Django 5.2.15 on 2026-06-09 07:45

from django.conf import settings
from django.db import migrations, models


def dedupe_per_company(apps, schema_editor):
    """旧表每公司可能多行(按月)；去重保留每公司一行，便于加 company 唯一约束。"""
    InvoiceQuota = apps.get_model("masterdata", "InvoiceQuota")
    seen = set()
    for q in InvoiceQuota.objects.order_by("company_id", "-id"):
        if q.company_id in seen:
            q.delete()
        else:
            seen.add(q.company_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_opening_locked'),
        ('masterdata', '0003_invoicequota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicequota',
            options={'ordering': ['company'], 'verbose_name': '开票额度', 'verbose_name_plural': '开票额度'},
        ),
        migrations.RemoveConstraint(
            model_name='invoicequota',
            name='uniq_quota_company_period',
        ),
        migrations.RunPython(dedupe_per_company, noop),
        migrations.RemoveField(
            model_name='invoicequota',
            name='period',
        ),
        migrations.AlterField(
            model_name='invoicequota',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='每月可开票额度(不含税)'),
        ),
        migrations.AddConstraint(
            model_name='invoicequota',
            constraint=models.UniqueConstraint(fields=('company',), name='uniq_quota_company'),
        ),
    ]
