# Generated by Django 5.2.15 on 2026-06-05 09:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='结存数量')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='结存金额')),
                ('avg_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='移动加权均价')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balance', to='masterdata.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存结存',
                'verbose_name_plural': '库存结存',
                'ordering': ['company', 'product__code'],
                'permissions': [('view_amount', '可查看库存金额')],
                'constraints': [models.UniqueConstraint(fields=('company', 'product'), name='uniq_stock_company_product')],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=4, verbose_name='方向')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='金额')),
                ('balance_quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='结存数量')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='结存金额')),
                ('balance_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='结存均价')),
                ('source_type', models.CharField(blank=True, max_length=32, verbose_name='来源单类型')),
                ('source_id', models.CharField(blank=True, max_length=32, verbose_name='来源单ID')),
                ('source_no', models.CharField(blank=True, max_length=64, verbose_name='来源单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='过账时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company', verbose_name='所属公司')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_moves', to='masterdata.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['company', 'product', 'created_at'], name='inventory_s_company_242f9e_idx')],
            },
        ),
    ]
