# Generated by Django 5.2.15 on 2026-06-05 23:56

import django.utils.timezone
from django.db import migrations, models


def backfill_date(apps, schema_editor):
    """旧流水：业务日期回填为过账时间(created_at)的日期。"""
    StockMove = apps.get_model("inventory", "StockMove")
    for m in StockMove.objects.all().iterator():
        m.date = m.created_at.date()
        m.save(update_fields=["date"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action'),
        ('inventory', '0001_initial'),
        ('masterdata', '0002_expensecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmove',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='业务日期'),
        ),
        migrations.RunPython(backfill_date, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['company', 'product', 'date'], name='inventory_s_company_623e5a_idx'),
        ),
    ]
