# Generated by Django 5.2.15 on 2026-06-05 13:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(choices=[('bank', '银行存款'), ('note_recv', '应收票据'), ('stock', '商品（金额）'), ('receivable', '应收账款'), ('payable', '应付账款')], max_length=16, verbose_name='对账类别')),
                ('as_of_date', models.DateField(verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='对账时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='core.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '对账记录',
                'verbose_name_plural': '对账记录',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_label', models.CharField(max_length=128, verbose_name='项目')),
                ('system_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='系统余额')),
                ('external_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='外部余额')),
                ('diff', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='差异')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='opening.reconciliationrun', verbose_name='对账记录')),
            ],
            options={
                'verbose_name': '对账明细',
                'verbose_name_plural': '对账明细',
            },
        ),
    ]
